image: gitpod/workspace-full-vnc
tasks:
  - init: |
      mkdir -p /workspace/.cache/Cypress
      ln -s /workspace/.cache/Cypress /home/gitpod/.cache/Cypress
      yarn install
  - before: ln -s /workspace/.cache/Cypress /home/gitpod/.cache/Cypress
jetbrains:
  phpstorm:
    plugins:
      - com.mallowigi
      - org.sonarlint.idea
      - com.tabnine.TabNine
    prebuilds: 
      version: stable
